disabled_rules:
- trailing_whitespace
- file_length
- identifier_name
- function_body_length
- force_cast
- multiple_closures_with_trailing_closure

excluded:
- Pods
- Koktail/Application/AppDelegate.swift
- Koktail/Application/SceneDelegate.swift
